const API=localStorage.getItem('apiUrl')||'https://fiberlink-backend.onrender.com/api';
let token=localStorage.getItem('adminToken')||'';let user=JSON.parse(localStorage.getItem('adminUser')||'null');let current='Dashboard';let cache={};
const el=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...opt.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Error');return d}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.append(d);setTimeout(()=>d.remove(),2500)}
function badge(s){const c=s==='Finalizada'?'b-done':s==='En proceso'?'b-progress':s==='Cancelada'?'b-cancel':'b-pending';return `<span class="badge ${c}">${esc(s)}</span>`}
function loginView(){el('#app').innerHTML=`<section class="login"><div class="login-brand"><img src="assets/fiberlink-logo.jpg"><h1>Sistema inteligente de órdenes de servicio técnico</h1><p>Gestión especializada para instalaciones, averías, migraciones y mantenimiento de internet por fibra óptica de Fiberlink.</p></div><div class="login-form"><form class="card-login" id="loginForm"><h2>Iniciar sesión</h2><p>Panel administrativo y de oficina</p><label>Correo</label><input id="email" placeholder="admin@fiberlink.pe"><label>Contraseña</label><div style="position:relative"><input id="password" type="password" style="padding-right:40px;width:100%;box-sizing:border-box"><button type="button" onclick="const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';this.textContent=p.type==='password'?'👁️':'🙈'" style="position:absolute;right:10px;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;font-size:16px;padding:0">👁️</button></div><p id="err" class="error"></p><button class="primary">Ingresar</button></form></div></section>`;el('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:el('#email').value,password:el('#password').value})}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.message);return x});token=d.token;user=d.user;localStorage.setItem('adminToken',token);localStorage.setItem('adminUser',JSON.stringify(user));shell();}catch(x){el('#err').textContent=x.message}}}
const nav=['Dashboard','Órdenes','Clientes','Técnicos','Materiales','Reportes','Auditoría'];
function shell(){el('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="assets/fiberlink-logo.jpg"><small>Internet y fibra óptica</small></div><nav class="nav">${nav.map(n=>`<button data-view="${n}">${n}</button>`).join('')}</nav><div class="userbox"><strong>${esc(user.name)}</strong><small>${esc(user.email)}</small><button class="logout">Cerrar sesión</button></div></aside><main class="content"><header class="topbar"><div><h1 id="title"></h1><p>Fiberlink · La Sierra Liberteña</p></div><div class="date-pill">${new Date().toLocaleDateString('es-PE',{dateStyle:'long'})}</div></header><div id="view"></div></main></div><div id="modal"></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));el('.logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}catch{}localStorage.clear();token='';user=null;loginView()};go('Dashboard')}
function setActive(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===current));el('#title').textContent=current}
async function go(v){current=v;setActive();el('#view').innerHTML='<div class="panel">Cargando...</div>';try{if(v==='Dashboard')await dashboard();if(v==='Órdenes')await orders();if(v==='Clientes')await resource('clients','Clientes');if(v==='Técnicos')await resource('technicians','Técnicos');if(v==='Materiales')await resource('materials','Materiales');if(v==='Reportes')await reports();if(v==='Auditoría')await audit()}catch(e){el('#view').innerHTML=`<div class="panel error">${esc(e.message)}</div>`}}
async function dashboard(){const d=await api('/dashboard');cache.dashboard=d;el('#view').innerHTML=`<section class="cards">${[['Órdenes hoy',d.totalOrders],['Pendientes',d.pending],['En proceso',d.inProgress],['Finalizadas',d.completed],['Técnicos activos',d.activeTechnicians],['Stock bajo',d.lowStock]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong><small>Información actual</small></article>`).join('')}</section><section class="grid2"><article class="panel"><h2>Órdenes recientes</h2>${orderTable(d.recentOrders)}</article><article class="panel"><h2>Estado de técnicos</h2><div class="status-list">${d.technicians.map(t=>`<div class="status-row"><span><i class="dot" style="background:${t.status==='Disponible'?'#0eaa61':'#ff6500'}"></i>${esc(t.name)}</span><b>${esc(t.status)}</b></div>`).join('')}</div></article></section><section class="grid2"><article class="panel"><h2>Órdenes por estado</h2><div class="chart">${[['Pend.',d.pending],['Proceso',d.inProgress],['Final.',d.completed],['Cancel.',d.cancelled]].map(([x,n])=>`<div class="bar" style="height:${Math.max(20,n*35)}px"><label>${x}</label></div>`).join('')}</div></article><article class="panel"><h2>Resumen del inventario</h2><div class="report-cards"><div class="report-card">Valor estimado<strong>S/ ${d.inventoryValue.toFixed(2)}</strong></div><div class="report-card">Materiales críticos<strong>${d.lowStock}</strong></div><div class="report-card">Clientes registrados<strong>${d.clients}</strong></div></div></article></section>`}
function orderTable(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Cliente</th><th>Servicio</th><th>Técnico</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${esc(o.code)}</b></td><td>${esc(o.client?.name)}</td><td>${esc(o.serviceType)}</td><td>${esc(o.technician?.name)}</td><td>${badge(o.status)}</td><td class="actions"><button onclick="showOrder(${o.id})">Ver</button><button onclick="editOrder(${o.id})">Editar</button></td></tr>`).join('')}</tbody></table></div>`}
async function orders(){const list=await api('/orders');cache.orders=list;el('#view').innerHTML=`<section class="panel"><div class="toolbar"><input id="q" class="search" placeholder="Buscar por código, cliente, técnico o dirección"><div class="filters"><select id="st"><option value="">Todos los estados</option><option>Pendiente</option><option>En proceso</option><option>Finalizada</option><option>Cancelada</option></select><button class="secondary" onclick="scanOCR()">Escanear Ficha (OCR)</button><button class="primary" onclick="newOrder()">+ Nueva orden</button></div></div><div id="orderList">${orderTable(list)}</div></section>`;el('#q').oninput=filterOrders;el('#st').onchange=filterOrders}
function filterOrders(){const q=el('#q').value.toLowerCase(),s=el('#st').value;const x=cache.orders.filter(o=>(!s||o.status===s)&&JSON.stringify(o).toLowerCase().includes(q));el('#orderList').innerHTML=orderTable(x)}
async function showOrder(id){const o=await api('/orders/'+id);
const wsBtn = o.status==='Finalizada' ? ` <button class="success" style="background:#25D366" onclick="mockWhatsApp(${o.id}, '${esc(o.client?.phone)}')">📱 WhatsApp al Cliente</button>` : '';
modal(`<div class="modal-head"><h2>${esc(o.code)} · ${esc(o.serviceType)}</h2><button onclick="closeModal()">×</button></div>
<div style="margin-bottom:15px"><button class="secondary" onclick="generatePDF(${o.id})">Generar PDF</button> <button class="secondary" onclick="analyzeAI(${o.id})">Analizar con IA</button>${wsBtn}</div>
<p>${badge(o.status)} Prioridad: <b>${esc(o.priority)}</b></p>
<div class="detail-grid">
  <div class="detail-box"><strong>Cliente</strong>${esc(o.client?.name)}<br>DNI: ${esc(o.client?.dni)}<br>📞 ${esc(o.client?.phone)}${o.client?.phone2?' / '+esc(o.client.phone2):''}<br>📍 ${esc(o.client?.address)}<br><small>${esc(o.client?.reference||'')}</small></div>
  <div class="detail-box"><strong>Técnico</strong>${esc(o.technician?.name)}<br>${esc(o.technician?.specialty)}<br>📞 ${esc(o.technician?.phone)}</div>
  <div class="detail-box"><strong>Servicio</strong>${esc(o.description)}<br><br><b>Programado:</b> ${new Date(o.scheduledAt).toLocaleString('es-PE')}</div>
  <div class="detail-box"><strong>Info. Técnica</strong>Sede: <b>${esc(o.sede||'-')}</b><br>Plan: <b>${esc(o.plan||'-')}</b><br>CTO: <b>${esc(o.cto||'-')}</b><br>Precinto: <b>${esc(o.precinto||'-')}</b></div>
</div>
<h3>Materiales registrados</h3>${o.materialsDetailed.length?o.materialsDetailed.map(x=>`<div class="material-line"><span>${esc(x.material?.name)}</span><b>${x.quantity} ${esc(x.material?.unit)}</b></div>`).join(''):'<p>Sin materiales.</p>'}
<h3>Observaciones / Notas Técnicas</h3><p>${esc(o.observations||'-')}</p><p>${esc(o.technicalNotes||'-')}</p>
<div id="aiResult" style="margin-top:15px;padding:10px;background:#eef5ff;border-radius:8px;display:none"></div>`)}

// Prototipo: Simular envío de WhatsApp
function mockWhatsApp(id, phone) {
  if (!phone || phone === 'undefined') return alert('El cliente no tiene teléfono registrado.');
  toast('🔄 Conectando con API de Meta/Twilio...');
  setTimeout(() => {
    toast(`✅ PDF y encuesta enviados por WhatsApp al ${phone}`);
  }, 2000);
}
async function newOrder(){const [clients,techs]=await Promise.all([api('/clients'),api('/technicians')]);
modal(`<div class="modal-head"><h2>Nueva Orden de Servicio Técnico</h2><button onclick="closeModal()">×</button></div>
<form id="orderForm" class="form-grid">
  <label>Cliente<select name="clientId">${clients.map(x=>`<option value="${x.id}">${esc(x.name)} – ${esc(x.address)}</option>`).join('')}</select></label>
  <label>Técnico<select name="technicianId">${techs.map(x=>`<option value="${x.id}">${esc(x.name)} (${esc(x.zone)})</option>`).join('')}</select></label>
  <label>Tipo de servicio
    <select name="serviceType">
      <option>Instalación</option>
      <option>Avería</option>
      <option>Migración</option>
      <option>Reconexión</option>
      <option>Traslado</option>
      <option>Anexo</option>
      <option>Recojo de equipo</option>
    </select>
  </label>
  <label>Prioridad<select name="priority"><option>Media</option><option>Alta</option><option>Baja</option></select></label>
  <label>Fecha programada<input name="scheduledAt" type="datetime-local" required></label>
  <label>Sede<input name="sede" placeholder="Ej: Otuzco, Julcán, Salpo"></label>
  <label>Plan contratado<input name="plan" placeholder="Ej: Cable Hogar, Duo Hogar"></label>
  <label>CTO<input name="cto" placeholder="Ej: CTO 76"></label>
  <label>Precinto<input name="precinto" placeholder="Ej: P-082"></label>
  <label class="span2">Descripción del trabajo<textarea name="description" required></textarea></label>
  <label class="span2">Observaciones adicionales<textarea name="observations"></textarea></label>
  <div class="span2 save-row"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Crear orden</button></div>
</form>`);
el('#orderForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.clientId=Number(d.clientId);d.technicianId=Number(d.technicianId);await api('/orders',{method:'POST',body:JSON.stringify(d)});closeModal();toast('Orden creada');orders()}}
async function editOrder(id){const o=await api('/orders/'+id);modal(`<div class="modal-head"><h2>Editar ${esc(o.code)}</h2><button onclick="closeModal()">×</button></div><form id="editOrder" class="form-grid"><label>Estado<select name="status">${['Pendiente','En proceso','Finalizada','Cancelada'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Prioridad<select name="priority">${['Baja','Media','Alta'].map(s=>`<option ${s===o.priority?'selected':''}>${s}</option>`).join('')}</select></label><label class="span2">Descripción<textarea name="description">${esc(o.description)}</textarea></label><label class="span2">Observaciones<textarea name="observations">${esc(o.observations||'')}</textarea></label><div class="span2 save-row"><button class="primary">Guardar</button></div></form>`);el('#editOrder').onsubmit=async e=>{e.preventDefault();await api('/orders/'+id,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal();toast('Orden actualizada');orders()}}
const meta={
  clients:{title:'Clientes',cols:['name','dni','phone','address','status'],fields:[['name','Nombre'],['dni','DNI'],['phone','Teléfono 1'],['phone2','Teléfono 2'],['email','Correo'],['address','Dirección'],['district','Distrito'],['reference','Referencia'],['status','Estado']]},
  technicians:{title:'Técnicos',cols:['name','phone','specialty','zone','status'],fields:[['name','Nombre'],['dni','DNI'],['phone','Teléfono'],['email','Correo'],['specialty','Especialidad'],['zone','Zona'],['vehicle','Vehículo'],['status','Estado']]},
  materials:{title:'Materiales',cols:['code','name','category','stock','minStock','unit','price'],fields:[['code','Código'],['name','Material'],['category','Categoría'],['stock','Stock'],['minStock','Stock mínimo'],['unit','Unidad'],['price','Precio']]}
};async function resource(key,title){const rows=await api('/'+key);cache[key]=rows;const m=meta[key];el('#view').innerHTML=`<section class="panel"><div class="toolbar"><input class="search" id="rq" placeholder="Buscar en ${title.toLowerCase()}"><button class="primary" onclick="resourceForm('${key}')">+ Nuevo</button></div><div id="rtable">${resourceTable(key,rows)}</div></section>`;el('#rq').oninput=e=>el('#rtable').innerHTML=resourceTable(key,rows.filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())))}
function resourceTable(key,rows){const m=meta[key];return `<div class="table-wrap"><table class="data-table"><thead><tr>${m.cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.map(x=>`<tr>${m.cols.map(c=>`<td>${esc(x[c])}</td>`).join('')}<td class="actions"><button onclick="resourceForm('${key}',${x.id})">Editar</button><button onclick="deleteResource('${key}',${x.id})">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`}
function resourceForm(key,id){const m=meta[key],x=id?cache[key].find(y=>y.id===id):{};modal(`<div class="modal-head"><h2>${id?'Editar':'Nuevo'} ${m.title}</h2><button onclick="closeModal()">×</button></div><form id="resourceForm" class="form-grid">${m.fields.map(([k,l])=>`<label>${l}<input name="${k}" value="${esc(x[k]??'')}"></label>`).join('')}<div class="span2 save-row"><button class="primary">Guardar</button></div></form>`);el('#resourceForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));for(const k of ['stock','minStock','price'])if(k in d)d[k]=Number(d[k]);await api('/'+key+(id?'/'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(d)});closeModal();toast('Registro guardado');resource(key,m.title)}}
async function deleteResource(key,id){if(!confirm('¿Eliminar este registro?'))return;await api('/'+key+'/'+id,{method:'DELETE'});toast('Registro eliminado');resource(key,meta[key].title)}
async function reports(){const d=await api('/dashboard'),orders=await api('/orders'),mats=await api('/materials');const services={};orders.forEach(o=>services[o.serviceType]=(services[o.serviceType]||0)+1);el('#view').innerHTML=`<section class="report-cards"><div class="report-card">Órdenes registradas<strong>${d.totalOrders}</strong></div><div class="report-card">Tasa de cierre<strong>${d.totalOrders?Math.round(d.completed/d.totalOrders*100):0}%</strong></div><div class="report-card">Valor inventario<strong>S/ ${d.inventoryValue.toFixed(2)}</strong></div></section><section class="grid2" style="margin-top:18px"><article class="panel"><h2>Servicios por tipo</h2>${Object.entries(services).map(([a,b])=>`<div class="status-row"><span>${esc(a)}</span><b>${b}</b></div>`).join('')}</article><article class="panel"><h2>Alertas de stock</h2>${mats.filter(x=>x.stock<=x.minStock).map(x=>`<div class="status-row"><span>${esc(x.name)}</span><b>${x.stock} ${esc(x.unit)}</b></div>`).join('')||'<p>Sin alertas.</p>'}</article></section>`}
async function audit(){const rows=await api('/audit');el('#view').innerHTML=`<section class="panel"><h2>Auditoría de acciones</h2><div class="table-wrap"><table class="data-table audit"><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>ID</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.at).toLocaleString('es-PE')}</td><td>${esc(x.user)}</td><td>${esc(x.action)}</td><td>${esc(x.entity)}</td><td>${x.entityId}</td></tr>`).join('')}</tbody></table></div></section>`}
function modal(html){el('#modal').innerHTML=`<div class="modal"><div class="modal-card">${html}</div></div>`}function closeModal(){el('#modal').innerHTML=''}
async function scanOCR(){toast('Escaneando documento...');try{const r=await api('/ocr/procesar',{method:'POST'});if(r.ok)modal(`<div class="modal-head"><h2>Resultado OCR</h2><button onclick="closeModal()">×</button></div><p>Se ha detectado la siguiente información:</p><pre style="background:#f4f7fb;padding:10px;border-radius:8px">${JSON.stringify(r.textoExtraido,null,2)}</pre><div class="save-row"><button class="primary" onclick="closeModal();newOrder()">Crear orden con estos datos</button></div>`);}catch(e){toast('Error OCR')}}
async function generatePDF(id){toast('Generando PDF...');try{const r=await api('/orders/'+id+'/pdf');if(r.ok){toast(r.message);setTimeout(()=>window.open(API.replace('/api','')+r.url,'_blank'),1000);}}catch(e){toast('Error al generar PDF')}}
async function analyzeAI(id){toast('Analizando...');try{const o=await api('/orders/'+id);const r=await api('/ai/diagnostico',{method:'POST',body:JSON.stringify({sintoma:o.description})});if(r.ok){const res=document.getElementById('aiResult');if(res){res.style.display='block';res.innerHTML=`<strong>Recomendación IA:</strong><br>${esc(r.diagnostico)}<br><br><strong>Materiales:</strong> ${r.materialesRecomendados.join(', ')}`;}}}catch(e){toast('Error en IA')}}
window.showOrder=showOrder;window.editOrder=editOrder;window.newOrder=newOrder;window.resourceForm=resourceForm;window.deleteResource=deleteResource;window.closeModal=closeModal;window.scanOCR=scanOCR;window.generatePDF=generatePDF;window.analyzeAI=analyzeAI;
if(token&&user)shell();else loginView();
